"""empty message

Revision ID: a925273313f1
Revises: 3b0137acd19a
Create Date: 2023-09-01 10:25:29.521198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a925273313f1'
down_revision = '3b0137acd19a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint('email_constraint', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('email_constraint', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
